# Generated by Django 4.1.13 on 2024-09-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='loaisanpham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.loaisanpham'),
        ),
    ]
